/**
 * Self-hosted web fonts (Issue #168). Pure functions; scripts/fonts.ts does the I/O.
 *
 * Google Fonts serves Japanese families as ~120 unicode-range slices per weight so a page only
 * downloads the slices it actually renders. We keep exactly that split: the script fetches the
 * Google CSS, downloads every slice into public/fonts/ and writes public/fonts/fonts.css that
 * references only local files — so no request ever leaves the site (CSP: font-src 'self').
 * Both families are licensed under the SIL Open Font License 1.1 (public/fonts/OFL.txt).
 */

export interface FontFamilySpec {
  family: string;
  weights: number[];
}

/** Heading = Shippori Mincho, body = BIZ UDPGothic (tokens.css --font-head / --font-body). */
export const FONT_FAMILIES: readonly FontFamilySpec[] = [
  { family: "Shippori Mincho", weights: [700, 800] },
  { family: "BIZ UDPGothic", weights: [400, 700] },
];

export interface FontFace {
  family: string;
  weight: number;
  /**
   * Google's slice label: the `.N.woff2` index for the Japanese slices, or the subset name from the
   * preceding comment (`latin`, `cyrillic`, …) for the unnumbered ones. Same label = same range across weights.
   */
  slice: string;
  unicodeRange: string;
  sourceUrl: string;
}

const FACE_RE = /(?:\/\*\s*([\w-]+)\s*\*\/\s*)?@font-face\s*\{([^}]*)\}/g;

function prop(block: string, name: string): string | undefined {
  const m = new RegExp(`${name}\\s*:\\s*([^;]+);`).exec(block);
  return m?.[1]?.trim();
}

/** Parses the CSS Google Fonts returns to a woff2-capable browser into one entry per slice. */
export function parseGoogleFontsCss(css: string): FontFace[] {
  const faces: FontFace[] = [];
  for (const m of css.matchAll(FACE_RE)) {
    const block = m[2] ?? "";
    const family = prop(block, "font-family")?.replace(/^['"]|['"]$/g, "");
    const weight = Number(prop(block, "font-weight"));
    const src = prop(block, "src") ?? "";
    const url = /url\(([^)]+)\)\s*format\(['"]woff2['"]\)/.exec(src)?.[1];
    const unicodeRange = prop(block, "unicode-range");
    if (!family || !Number.isInteger(weight)) throw new Error(`fonts: @font-face without font-family / font-weight:\n${block}`);
    const spec = FONT_FAMILIES.find((f) => f.family === family);
    if (!spec) throw new Error(`fonts: unexpected family "${family}"`);
    if (!spec.weights.includes(weight)) throw new Error(`fonts: unexpected weight ${weight} for ${family}`);
    if (!url) throw new Error(`fonts: ${family} ${weight}: src is not a woff2 url (expected Google's sliced woff2 CSS)`);
    if (!unicodeRange) throw new Error(`fonts: ${family} ${weight}: no unicode-range (expected sliced CSS)`);
    const slice = /\.(\d+)\.woff2$/.exec(url)?.[1] ?? m[1];
    if (!slice) throw new Error(`fonts: cannot name the slice of ${url} (no .N.woff2 index and no /* subset */ comment)`);
    faces.push({ family, weight, slice, unicodeRange, sourceUrl: url });
  }
  return faces;
}

/** `Shippori Mincho` 700 slice 12 -> `shippori-mincho-700.12.woff2` */
export function sliceFileName(face: Pick<FontFace, "family" | "weight" | "slice">): string {
  const slug = face.family.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return `${slug}-${face.weight}.${face.slice}.woff2`;
}

/**
 * fonts.css for public/fonts/. Faces are ordered by slice index first so the five faces that share a
 * unicode-range sit next to each other — gzip then stores each (long) range list roughly once.
 */
export function renderFontsCss(faces: FontFace[]): string {
  const familyIndex = (f: string) => FONT_FAMILIES.findIndex((s) => s.family === f);
  const sliceKey = (s: string) => (/^\d+$/.test(s) ? s.padStart(4, "0") : `~${s}`); // numbered first, then latin/cyrillic/… by name
  const sorted = [...faces].sort(
    (a, b) => (sliceKey(a.slice) < sliceKey(b.slice) ? -1 : sliceKey(a.slice) > sliceKey(b.slice) ? 1 : 0) || familyIndex(a.family) - familyIndex(b.family) || a.weight - b.weight,
  );
  const blocks = sorted.map(
    (f) =>
      `@font-face {\n  font-family: "${f.family}";\n  font-style: normal;\n  font-weight: ${f.weight};\n  font-display: swap;\n  src: url(${sliceFileName(f)}) format("woff2");\n  unicode-range: ${f.unicodeRange};\n}`,
  );
  return `/* Generated by apps/web/scripts/fonts.ts (Issue #168) — do not edit by hand.\n   Shippori Mincho / BIZ UDPGothic, SIL Open Font License 1.1: see OFL.txt in this directory. */\n${blocks.join("\n")}\n`;
}
