import { Links, Meta, Outlet, Scripts, ScrollRestoration } from "react-router";
import "./styles/tokens.css";
import { THEME_STORAGE_KEY } from "./components/ThemeToggle";
import { BRAND } from "./lib/brand-colors";
import { installPromptInit } from "./lib/install-prompt";
import { robotsMeta, siteOrigin } from "./lib/seo";

/** staging build (#127): every page carries noindex; null on production / origin-less builds. */
const robots = robotsMeta(siteOrigin());

/**
 * #168: Shippori Mincho / BIZ UDPGothic are served from this site (public/fonts/, generated by
 * scripts/fonts.ts as unicode-range slices), so a visit sends nothing to Google. CSP: font-src 'self'.
 */
export const FONTS_CSS_HREF = "/fonts/fonts.css";

export function links() {
  return [
    { rel: "stylesheet", href: FONTS_CSS_HREF },
    // #129: SVG ファビコン（ダーク対応）を優先し、ICO は旧ブラウザ向け。PNG/ICO はビルド時生成（scripts/brand-assets.ts）
    { rel: "icon", href: "/favicon.svg", type: "image/svg+xml" },
    { rel: "icon", href: "/favicon.ico", sizes: "48x48" },
    { rel: "apple-touch-icon", href: "/apple-touch-icon.png", sizes: "180x180" },
    { rel: "manifest", href: "/site.webmanifest" },
  ];
}

/** ブラウザ UI の色（墨藍）。各ルートの meta() は親の meta を継がないので head に直接書く。 */
export const THEME_COLOR = BRAND.ink;

/** 保存済みテーマをハイドレーション前に html へ付与し、ちらつきを防ぐ。 */
const themeInit = `try{var t=localStorage.getItem(${JSON.stringify(THEME_STORAGE_KEY)});if(t==="light"||t==="dark")document.documentElement.setAttribute("data-theme",t)}catch(e){}`;

export default function Root() {
  return (
    <html lang="ja">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content={THEME_COLOR} />
        {robots && <meta name={robots.name} content={robots.content} />}
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
        {/* #191: beforeinstallprompt をハイドレーション前に捕捉し、ブラウザの自動インストール案内を止める */}
        <script dangerouslySetInnerHTML={{ __html: installPromptInit }} />
        <Meta />
        <Links />
      </head>
      <body>
        <Outlet />
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}
