import { Links, Meta, Outlet, Scripts, ScrollRestoration } from "react-router";
import "./styles/tokens.css";
import { THEME_STORAGE_KEY } from "./components/ThemeToggle";
import { BRAND } from "./lib/brand-colors";
import { installPromptInit } from "./lib/install-prompt";
import { robotsMeta, SITE_NAME, siteOrigin } from "./lib/seo";

/** staging build (#127): every page carries noindex; null on production / origin-less builds. */
const robots = robotsMeta(siteOrigin());

/**
 * #168: Shippori Mincho / BIZ UDPGothic are served from this site (public/fonts/, generated by
 * scripts/fonts.ts as unicode-range slices), so a visit sends nothing to Google. CSP: font-src 'self'.
 */
export const FONTS_CSS_HREF = "/fonts/fonts.css";

export function links() {
  return [
    { rel: "stylesheet", href: FONTS_CSS_HREF },
    // #129: SVG ファビコン（ダーク対応）を優先し、ICO は旧ブラウザ向け。PNG/ICO はビルド時生成（scripts/brand-assets.ts）
    { rel: "icon", href: "/favicon.svg", type: "image/svg+xml" },
    { rel: "icon", href: "/favicon.ico", sizes: "48x48" },
    { rel: "apple-touch-icon", href: "/apple-touch-icon.png", sizes: "180x180" },
    { rel: "manifest", href: "/site.webmanifest" },
  ];
}

/** ブラウザ UI の色（墨藍）。各ルートの meta() は親の meta を継がないので head に直接書く。 */
export const THEME_COLOR = BRAND.ink;

/** 保存済みテーマをハイドレーション前に html へ付与し、ちらつきを防ぐ。 */
const themeInit = `try{var t=localStorage.getItem(${JSON.stringify(THEME_STORAGE_KEY)});if(t==="light"||t==="dark")document.documentElement.setAttribute("data-theme",t)}catch(e){}`;

/**
 * HTML の外枠。Root と HydrateFallback の両方がこれを描く。
 * root ルートに HydrateFallback を置くと、React Router は **Root の代わりに** それを描く（Outlet の中身が
 * 差し替わるのではない）ので、フォールバック側も `<html>` から `<Scripts />` まで自分で書く必要がある。
 * 片方だけが shell を持つと SPA モードのビルドが `Did you forget to include <Scripts/>` で落ちる。
 */
/** skip link の飛び先。ルートごとの <main> に id を振らずに済むよう、shell 側で1つ持つ */
const MAIN_ID = "main";

function Document({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content={THEME_COLOR} />
        {robots && <meta name={robots.name} content={robots.content} />}
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
        {/* #191: beforeinstallprompt をハイドレーション前に捕捉し、ブラウザの自動インストール案内を止める */}
        <script dangerouslySetInnerHTML={{ __html: installPromptInit }} />
        <Meta />
        <Links />
      </head>
      <body>
        {/*
          Issue 394: skip link。無いと、キーボード利用者は**ページを開くたびに**ヘッダのリンクを
          全部たどってから本文に着く（議員ページはタブが6つあるので、その手前を毎回通る）。
          body の最初に置くので Tab 1回で届き、フォーカスが当たったときだけ見える（pages.css）。
          axe はこれを必須項目として出さない——本番 13 ページの計測は違反 0 件だった。
        */}
        <a className="skip-link" href={`#${MAIN_ID}`}>
          本文へ移動
        </a>
        <div id={MAIN_ID} tabIndex={-1}>
          {children}
        </div>
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

/**
 * Issue #325: ハイドレーション前に見せる画面。定義しないと React Router が自前の既定フォールバックを使い、
 * プリレンダー無しのページ（/__spa-fallback.html）が `<html lang="en">` / `<title>Loading...</title>` になり、
 * さらに `💿 Hey developer …` を本番のコンソールに出していた。
 * nginx はこの HTML を 404 の本文としても返す（deploy/nginx/site.conf の error_page）ので、
 * <title> にサイト名が入ること（外形監視 probe.sh の検査）と noindex が要る。両方 meta() が付ける。
 */
export function HydrateFallback() {
  return (
    <Document>
      <main className="page" aria-busy="true">
        <p className="note">読み込んでいます…</p>
      </main>
    </Document>
  );
}

/** 404 の本文にもなる shell（#325）なので、既定の <title> はサイト名入り・noindex にする。 */
export function meta() {
  return [{ title: SITE_NAME }, { name: "robots", content: "noindex" }];
}

export default function Root() {
  return (
    <Document>
      <Outlet />
    </Document>
  );
}
