#!/usr/bin/env bash
# Cloudflare IP allow-list for the host nginx (Issue #163). Run as root on the VPS:
#   bash deploy/run-remote.sh deploy/cloudflare-allowlist.sh                                        # update once
#   scp deploy/cloudflare-allowlist.sh "${VPS_SSH_HOST:-sakura-vps}":/tmp/ && ssh "${VPS_SSH_HOST:-sakura-vps}" \
#     'sudo bash /tmp/cloudflare-allowlist.sh --install-cron && rm /tmp/cloudflare-allowlist.sh'         # + weekly cron
#
# staging.giinrecord.jp sits behind Cloudflare Access (the Cloudflare proxy, orange cloud). The origin must refuse
# everything that does not come through Cloudflare, otherwise Access is bypassed by talking to the VPS directly.
# This script turns https://www.cloudflare.com/ips-v4 and /ips-v6 into
#   /etc/nginx/snippets/giinrecord-cloudflare-allow.conf        allow <cidr>; … deny all;
# which deploy/vps-setup.sh includes in the STAGING 443 `location /` only (production is open to everyone).
#
# Safety:
#   - every fetched line must be a strictly well-formed CIDR (IPv4 a.b.c.d/0-32 with octets ≤ 255, or IPv6 hex groups
#     with /0-128); anything else (HTML error page, redirect, an injected `;`) aborts BEFORE anything is written
#   - an empty list aborts too (an empty allow-list would deny Cloudflare itself and lock staging out)
#   - the snippet is written to a temp file in the same directory and renamed into place (atomic);
#     `nginx -t` gates the reload and a failing test puts the previous snippet back (or removes the new one on
#     first install) — the live config is never left pointing at a broken snippet
#   - an unchanged snippet is not rewritten and nginx is not reloaded (the weekly cron is a no-op most weeks)
#   - --install-cron copies this script to /usr/local/lib/giinrecord-cloudflare-allowlist.sh (root-owned, 755: the root
#     cron must never execute a file the deploy user could edit) and writes /etc/cron.d/giinrecord-cloudflare-allowlist
# Nothing here touches sites-available/, certificates or any other site on the shared host.
#   Tests: deploy/test/cloudflare-allowlist.test.sh (CF_ALLOWLIST_PREFIX roots every path; curl/nginx/systemctl are stubs)
set -euo pipefail

PREFIX="${CF_ALLOWLIST_PREFIX:-}"
SNIPPET_DIR="$PREFIX/etc/nginx/snippets"
SNIPPET="$SNIPPET_DIR/giinrecord-cloudflare-allow.conf"
LIB="$PREFIX/usr/local/lib/giinrecord-cloudflare-allowlist.sh"
CRON="$PREFIX/etc/cron.d/giinrecord-cloudflare-allowlist"
V4_URL=https://www.cloudflare.com/ips-v4
V6_URL=https://www.cloudflare.com/ips-v6
TIMEOUT=${CF_ALLOWLIST_TIMEOUT:-30}

usage() { echo "usage: cloudflare-allowlist.sh [--install-cron]" >&2; }

INSTALL_CRON=0
for arg in "$@"; do
  case "$arg" in
    --install-cron) INSTALL_CRON=1 ;;
    *) usage; exit 2 ;;
  esac
done

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

# fetch <url> <outfile>: curl with a hard timeout, no redirects (the lists are plain text at a fixed URL)
fetch() { curl -sSf --max-time "$TIMEOUT" -o "$2" "$1"; }

# valid_v4 <line> / valid_v6 <line>: strict CIDR syntax only (no spaces, comments, CR or nginx tokens).
valid_v4() {
  local re='^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])/(3[0-2]|[12]?[0-9])$'
  [[ "$1" =~ $re ]]
}
valid_v6() {
  [[ "$1" == */* ]] || return 1
  local addr=${1%/*} mask=${1##*/} rest groups=0 g group
  [[ "$mask" =~ ^(12[0-8]|1[01][0-9]|[1-9]?[0-9])$ ]] || return 1
  [[ "$addr" =~ ^[0-9a-fA-F:]+$ ]] || return 1
  rest=${addr//::/}
  [[ "$rest" != *::* ]] || return 1                       # at most one '::'
  [[ "$addr" != *:::* ]] || return 1
  IFS=: read -r -a g <<< "$addr"
  for group in "${g[@]}"; do
    [[ -z "$group" ]] && continue
    [[ "$group" =~ ^[0-9a-fA-F]{1,4}$ ]] || return 1
    groups=$((groups+1))
  done
  if [[ "$addr" == *::* ]]; then [[ $groups -le 7 ]]; else [[ $groups -eq 8 ]]; fi
}

# validate <file> <v4|v6>: every line a CIDR of that family, at least one line; prints the lines
validate() {
  local file=$1 family=$2 n=0 line
  while IFS= read -r line || [ -n "$line" ]; do
    if ! "valid_$family" "$line"; then
      echo "!! $family list contains an invalid line ($(printf '%q' "$line" | cut -c1-60)); nothing written." >&2
      return 1
    fi
    n=$((n+1))
  done < "$file"
  if [ "$n" -eq 0 ]; then echo "!! $family list is empty; nothing written (would deny Cloudflare itself)." >&2; return 1; fi
  cat "$file"
}

build_snippet() {
  fetch "$V4_URL" "$TMP/v4" || { echo "!! fetch of $V4_URL failed; snippet unchanged." >&2; return 1; }
  fetch "$V6_URL" "$TMP/v6" || { echo "!! fetch of $V6_URL failed; snippet unchanged." >&2; return 1; }
  {
    echo "# Cloudflare IP ranges ($V4_URL, $V6_URL) — generated by deploy/cloudflare-allowlist.sh (giinrecord #163)."
    echo "# Included by the staging server block only. Do not edit: regenerated weekly by /etc/cron.d/giinrecord-cloudflare-allowlist."
    validate "$TMP/v4" v4 | sed 's/^/allow /; s/$/;/'
    validate "$TMP/v6" v6 | sed 's/^/allow /; s/$/;/'
    echo "deny all;"
  } > "$TMP/snippet"
}

# install_snippet: atomic replace, nginx -t gate, rollback on failure, reload only when something changed
install_snippet() {
  if [ -f "$SNIPPET" ] && cmp -s "$TMP/snippet" "$SNIPPET"; then
    echo "$SNIPPET unchanged ($(grep -c '^allow ' "$SNIPPET") ranges); nginx not reloaded."
    return 0
  fi
  mkdir -p "$SNIPPET_DIR"
  local new backup=""
  new=$(mktemp "$SNIPPET_DIR/.giinrecord-cloudflare-allow.conf.tmp.XXXXXX")
  cat "$TMP/snippet" > "$new"; chmod 644 "$new"
  if [ -f "$SNIPPET" ]; then backup="$TMP/snippet.bak"; cp -p "$SNIPPET" "$backup"; fi
  mv -f "$new" "$SNIPPET"
  if nginx -t; then
    systemctl reload nginx
    echo "$SNIPPET updated ($(grep -c '^allow ' "$SNIPPET") ranges); nginx reloaded."
  else
    if [ -n "$backup" ]; then cp -p "$backup" "$SNIPPET"; else rm -f "$SNIPPET"; fi
    echo "!! nginx -t failed with the new snippet; previous state restored, nginx NOT reloaded." >&2
    exit 1
  fi
}

install_cron() {
  local self=${BASH_SOURCE[0]:-}
  if [ ! -f "$self" ]; then
    echo "!! --install-cron needs the script as a file (not stdin): scp deploy/cloudflare-allowlist.sh to the host and run sudo bash /path/cloudflare-allowlist.sh --install-cron" >&2
    exit 2
  fi
  install -d -m 755 "$(dirname "$LIB")" "$(dirname "$CRON")"
  install -m 755 "$self" "$LIB"
  if [ "$(id -u)" = 0 ]; then chown root:root "$LIB"; fi
  cat > "$CRON" <<CRON
# giinrecord #163: refresh the Cloudflare IP allow-list of the staging server block once a week (Monday 04:20, root).
# The script validates every range, writes atomically and reloads nginx only when nginx -t passes.
20 4 * * 1 root test -x /usr/local/lib/giinrecord-cloudflare-allowlist.sh && /usr/local/lib/giinrecord-cloudflare-allowlist.sh > /dev/null
CRON
  chmod 644 "$CRON"
  echo "weekly cron installed: $CRON (runs $LIB)"
}

main() {
  build_snippet
  install_snippet
  if [ "$INSTALL_CRON" = 1 ]; then install_cron; fi
}

main
